services:
  app_postgis:
    image: postgis/postgis:latest
    container_name: app_postgis
    env_file: ./.env
    volumes:
      - app_postgis:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  app_api:
    container_name: app_api
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    build: ./app
    env_file: ./.env
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8002:8000
    depends_on:
      - app_postgis

  app_redis:
    container_name: app_redis
    image: redis
    ports:
      - 6379:6379

  app_bg_tasks:
    container_name: app_bg_tasks
    build: ./app
    depends_on:
      - app_postgis
    env_file: .env
    command: saq saq_tasks.main.settings --web

volumes:
  app_postgis:
